### ISSUE TITLE
xpad.ko not included in modules

### ISSUE THREAD

**Issue by whazaaa** [ArchiDroid/ArchiDroid#62]
I can't use my wired xbox 360 controller because it isn't recognised (using otg cable)

**Comment by JustArchi** [comment]
Done in https://github.com/ArchiDroid/ArchiKernel/commit/d0c539705a0c48aaec081248717a4d14e947b4e1, it'll be available from next AK snapshot.

**Comment by whazaaa** [comment]
thank you very much I tried fixing it myself but it wouldnt work even crashed my phone so im very greatfull

Date: Thu, 23 Apr 2015 15:39:02 -0700

**Comment by JustArchi** [comment]
Done.
https://github.com/ArchiDroid/ArchiDroid/commit/8ccd3e54b0b141fb5494575dfb828dd05452d981

**Comment by whazaaa** [comment]
Im using terminal with command
Su
Insmod location/xpad.ko
And im getting failed exec format error
Do you know how to get this working?


--- Oorspronkelijk bericht ---

Van: "Łukasz Domeradzki" <notifications@github.com>
Verzonden: 25 april 2015 02:01
Aan: "ArchiDroid/ArchiDroid" <ArchiDroid@noreply.github.com>
CC: "josja de greef" <josjaxbox360@live.nl>
Onderwerp: Re: [ArchiDroid] xpad.ko not included in modules (#62)

Done.
https://github.com/ArchiDroid/ArchiDroid/commit/8ccd3e54b0b141fb5494575dfb828dd05452d981

---

**Comment by JustArchi** [comment]
su
insmod /system/lib/modules/xpad.ko
lsmod

lsmod should report that xpad.ko is loaded. It works for me.

**Comment by whazaaa** [comment]
This is what i get

--- Oorspronkelijk bericht ---

Van: "Łukasz Domeradzki" <notifications@github.com>
Verzonden: 26 april 2015 10:11 PM
Aan: "ArchiDroid/ArchiDroid" <ArchiDroid@noreply.github.com>
CC: "josja de greef" <josjaxbox360@live.nl>
Onderwerp: Re: [ArchiDroid] xpad.ko not included in modules (#62)

su
insmod /system/lib/modules/xpad.ko
lsmod

lsmod should report that xpad.ko is loaded. It works for me.

---

**Comment by whazaaa** [comment]
i got it working with the BOEFFLA kernelthank you very much

Date: Sun, 26 Apr 2015 13:11:03 -0700
