### ISSUE TITLE
Spirit FM doesn't show up

### ISSUE THREAD

**Issue by henri-hulski** [ArchiDroid/ArchiDroid#76]
First thanks for your wonderful ROM. I just installed it on my "new" Galaxy S3.
I configured it as clean as possible and it's great. 

Only one issue, I marked Spirit FM for install, but couldn't find it nowhere on the phone. 

Regards, 
Henri

**Comment by JustArchi** [comment]
http://forum.xda-developers.com/showpost.php?p=61105589&postcount=9188
http://forum.xda-developers.com/showpost.php?p=61930375&postcount=9292

**Comment by JustArchi** [comment]
Solution: Install manually or convince Mike into adding support for installing as system APK.
