### ISSUE TITLE
Dex-preoptimization for ART breaks Xposed

### ISSUE THREAD

**Issue by Sameer26** [ArchiDroid/ArchiDroid#78]
I flashed experimental build with xposed and got bootloop then I checked temasek ROM thread in temasek ROM thread DarkenedSky said that Dex-preoptimization for ART breaks Xposed. I don't use Xposed but reporting it for users who use Xposed.

**Comment by JustArchi** [comment]
Making AD to work with xposed is the last thing I'll be doing.
