### ISSUE TITLE
3.1.5 Still rebooting

### ISSUE THREAD

**Issue by Translator5** [ArchiDroid/ArchiDroid#81]
Version 3.1.5 for S3 (int) is unstable as fuck.
I works as long as you do not shut-down or reboot you device, if you do once reboot it is in a boot-circle. To exit you have to clean your dalvin cache, but you will lose you data (e.g. chat)
Already for more than 2 months I cant reboot.

Edit: I've got it!
Disable LiveBoot Root permissions, and it will work fine!

**Comment by JustArchi** [comment]
AD 3.1.5 is EOL.
